### ISSUE TITLE
cutting a new release

### ISSUE THREAD

**Issue by threepointone** [cloudflare/kv-asset-handler#262]
I'm going to cut a release soon (today, or tomorrow at the latest), and I want to know whether it's safe to do so. @Cherry, looks like you have a bunch of commits that you've landed. Is there anything preventing me from cutting a release? Should it be a patch or a minor (or even a major?)

**Comment by Cherry** [comment]
Everything should be good for release, thanks @threepointone! If you need any help with the changelog, let me know.

We may want to update the README with some instructions for how to use in modules when #261 lands. As for the versioning, since we're in 0.x, it doesn't overly matter. As long as there's no breaking changes, I think a 0.2.0 or even 1.0.0 would be fine - we've been in 0.x for far too long 😅

**Comment by threepointone** [comment]
If there aren't any breaking changes, I'll mark it as 0.2.0.

**Comment by Cherry** [comment]
No breaking changes on my end either.

The only functional fixes/changes were;

- https://github.com/cloudflare/kv-asset-handler/pull/243
- and https://github.com/cloudflare/kv-asset-handler/pull/254

All other commits were maintenance such as reducing the output size in https://github.com/cloudflare/kv-asset-handler/commit/92c8e6e0bd9d3fb73b6628adca9fcea2e7716562.

**Comment by threepointone** [comment]
wonderful, thank you!

**Comment by threepointone** [comment]
Nat said she'd do the release, thank you so very much @nataliescottdavidson!

**Comment by threepointone** [comment]
released 0.2.0, ES Modules wooo
