### ISSUE TITLE
rename types.ts to index.d.ts

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/kv-asset-handler#65]

**Comment by victoriabernard92** [comment]
Since this repo is already in typescript, there is actually no need for ambient type declarations. After build, they already live at `dist/index.d.ts`, `dist/types.d.ts` etc... 
Also `types.ts` contains simple implementation for the custom error classes as well as a few type defs. I do not see any value in moving this to two different files, so closing this.
